apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: {{ .Values.kafka.storage.type}}
    {{ if eq .Values.kafka.storage.type "persistent-claim" }}
      size: {{ .Values.kafka.storage.size }}
      deleteClaim: {{ .Values.kafka.storage.deleteClaim }}
    {{ else if eq .Values.kafka.storage.type "jbod"}}
      volumes:
      {{ range $i := until (int .Values.kafka.replicas) }}
        - id: {{ . }}
          type: {{ $.Values.kafka.storage.volume.type }}
          size: {{ $.Values.kafka.storage.volume.size }}
          deleteClaim: {{ $.Values.kafka.storage.volume.deleteClaim }}
      {{ end }}
    {{ end }}
    resources:
      requests:
        memory: {{ .Values.kafka.resources.requests.memory | default "3Gi" | quote }}
        cpu: {{ .Values.kafka.resources.requests.cpu | default 1 | int }}
      limits:
         memory: {{ .Values.kafka.resources.limits.memory | default "5Gi" | quote }}
         cpu: {{ .Values.kafka.resources.limits.cpu | default 2 | int }}
    listeners:  
      {{ range $listener := .Values.kafka.listeners }}
      - name: {{ $listener.name }}
        type: {{ $listener.type }}
        tls: {{ $listener.tls }}
        port: {{ $listener.port }}
      {{ end }}
  
  zookeeper:
    replicas: 3
    storage:
      type: {{ .Values.zookeeper.storage.type}}
      {{ if eq .Values.zookeeper.storage.type "persistent-claim" }}
      size: {{ .Values.zookeeper.storage.size }}
      deleteClaim: {{ .Values.zookeeper.storage.deleteClaim }}
      {{ end }} 
    resources:
      requests:
        memory: {{ .Values.zookeeper.resources.requests.memory | default "3Gi" | quote }}
        cpu: {{ .Values.zookeeper.resources.requests.cpu | default 1 | int }}
      limits:
         memory: {{ .Values.zookeeper.resources.limits.memory | default "5Gi" | quote }}
         cpu: {{ .Values.zookeeper.resources.limits.cpu | default 2 | int }}

  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: {{ .Values.entityOperator | default "3Gi" | quote }}
          cpu: {{ .Values.entityOperator | default 1 | int }}
        limits:
          memory: {{ .Values.entityOperator | default "5Gi" | quote }}
          cpu: {{ .Values.entityOperator | default 2 | int }}
    userOperator:
      resources:
        requests:
          memory: {{ .Values.entityOperator | default "3Gi" | quote }}
          cpu: {{ .Values.entityOperator | default 1 | int }}
        limits:
          memory: {{ .Values.entityOperator | default "5Gi" | quote }}
          cpu: {{ .Values.entityOperator | default 2 | int }}