{{ if .Values.topics }}
{{- range $topic := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  partitions: {{  $topic.partitions }}
  replicas: {{ $topic.replicas}}
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
{{ end }}
{{ end }}