# // Cluster configs
namespace: kafkatst2
clusterName: final1

# // Kafka configuration
kafka:
  replicas: 3
  # // All storage types - Ephemeral, Persistent, JBOD(recommended for production).
  # // Read more about storage at - https://strimzi.io/docs/operators/latest/configuring.html#considerations-for-data-storage-str
  storage:
  # // For jbod, this configuration are for all replicas
    type: jbod
    volume:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
  # // External load balancer port
  externalPort: 9094
        
zookeeper:
   replicas: 3
   # // Jbod is not supported for zookeeper
   storage:
     type: persistent-claim
     size: 2Gi
     deleteClaim: false

topics:
  - name: testhelm
    replicas: 3
  - name: helm2u
    replicas: 1
