# // Cluster configs
namespace: kafka2
clusterName: kafka-poc

# // Kafka configuration
kafka:
  replicas: 3
  # // All storage types - Ephemeral, Persistent, JBOD
  # // Read more about storage at - https://strimzi.io/docs/operators/latest/configuring.html#considerations-for-data-storage-str
  storage:
  #   // example for persistent-claim
  #   type: persistent-claim
  #   size: 1Gi
  #   deleteClaim: true
    type: jbod
    volumes:
      - volid: 1
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
      - volid: 2
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
      - volid: 3
        type: persistent-claim
        size: 2Gi
        deleteClaim: false


zookeeper:
   replicas: 3
   # All storage types - Ephemeral, Persistent, JBOD
   # Read more about storage at - https://strimzi.io/docs/operators/latest/configuring.html#considerations-for-data-storage-str
   storage:
     type: persistent-claim
     size: 2Gi