apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-operator-to-clusters
spec:
  podSelector: {}
  egress:
    - ports:
        {{- range $port := .Values.egress.ports}}
        - protocol: {{ $port.protocol }}
          port: {{ $port.port }}
        {{ end }}
  policyTypes:
    - Egress